pipeline{
    agent any
    stages {
        stage('Build'){
            echo 'Building...'
            echo 'Building ${env.BUILD_ID}'
            echo $PATH
        }
        stage('testing'){
               echo 'testing!' 
        }
    }
}
